print("Comparing product prices:")
p1_name=str(input("phone 1:"))
p1_price=eval(input("phone 1 price:"))
p2_name=str(input("phone 2:"))
p2_price=eval(input("phone 2 price:"))
vat=0.15
p1_price=p1_price+(p1_price*vat)
p2_price=p2_price+(p2_price*vat)
print(p1_name,"price is equal to",p2_name,"price :",p1_price==p2_price)
print(p1_name,"price is less than",p2_name,"price :",p1_price<p2_price)
print(p1_name,"price is greater",p2_name,"price :",p1_price>p2_price)
