print("create you favourite list bro")
player=str(input("enter your favourite player name: "))
sport=str(input("enter your favourite sports:"))
city=str(input("enter your favourite city that you want to visit: "))
country=str(input("enter your favorite country:"))
print("your favourite player is: ",player)
print("your favourite sports is: ",sport)
print("your favourite city is: ",city)
print("your favourite country is: ",country)
